# Generated by Django 4.0.6 on 2022-07-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('u_nombres', models.CharField(max_length=50)),
                ('u_apellidos', models.CharField(max_length=50)),
                ('u_identificacion', models.CharField(max_length=15)),
                ('u_telefono', models.CharField(max_length=50)),
                ('u_email', models.CharField(max_length=50, unique=True)),
                ('u_imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Imagen de Empleado')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_userp', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['u_apellidos'],
            },
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('jefe', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('responsabilidades', models.TextField()),
                ('logros', models.TextField()),
                ('empleado_id_Ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.DateField()),
                ('estudios', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('empleado_id_Em', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='u_tipoDpocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuariosApp.tipodocumento'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='u_tipoSangre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuariosApp.tiposangre'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
