# Generated by Django 4.0.6 on 2022-07-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudios',
            options={'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'tipoDocumento', 'verbose_name_plural': 'tipoDocumentos'},
        ),
        migrations.AlterModelOptions(
            name='tiposangre',
            options={'verbose_name': 'tipoSangre', 'verbose_name_plural': 'tiposSangre'},
        ),
    ]
