# Generated by Django 4.0.6 on 2022-07-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0003_alter_estudios_fechas_alter_experiencia_fechas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='fechas',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fechas',
            field=models.DateField(),
        ),
    ]
